# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: "windows-latest"

steps:
  - powershell: |
      $REPO_PATH = $(Build.SourcesDirectory)
      write-verbose "path; $REPO_PATH"

  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node.js"

  - script: |
      yarn install
    displayName: "install dependencies"

  - script: |
      node bin/env.js
    displayName: Check environment

  - script: |
      yarn format:check
    displayName: "check code style"

  - script: |
      yarn lint
    displayName: "check code semantics"

  - powershell: |
      $REPO_PATH = $(Build.SourcesDirectory)
      $LOG_FILE_PATH = "$REPO_PATH\lib\a11y-snapshot\nvda.log"
      $NVDA_VENDOR = "$REPO_PATH\node_modules\screen-reader-testing-library\nvda-2020.2"
      $NVDA_BIN = "$NVDA_VENDOR\portable\nvda.exe"
      & $NVDA_BIN --log-file=$LOG_FILE_PATH --config-path=$NVDA_VENDOR\settings
      yarn a11y-snapshot --runInBand screen-reader.test.js
      & $NVDA_BIN -q
    displayName: "test"

  - task: Npm@1
    continueOnError: "true"
    inputs:
      command: publish
      publishEndpoint: github
    displayName: "publish if version changed"
