name: watch-material-ui

on: [repository_dispatch, push]

jobs:
  a11y-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: install
        run: yarn install
      - uses: ./actions/watch-material-ui
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
