name: watch-material-ui

on:
  push:
  repository_dispatch:
  schedule:
    # run every hour to catch new deploys of the default branch
    # netlify triggers no status check so I don't know
    # how I could be notified if it finishes a deploy of the default branch
    - cron: "0 * * * *"

defaults:
  run:
    shell: powershell

jobs:
  a11y-snapshot:
    runs-on: windows-latest
    env:
      NVDA_VENDOR: "${{ github.workspace }}\node_modules\screen-reader-testing-library\nvda-2020.2"
      # NVDA_BIN: "${{ env.NVDA_VENDOR }}\portable\nvda.exe"
      NVDA_BIN: "${{ github.workspace }}\node_modules\screen-reader-testing-library\nvda-2020.2\portable\nvda.exe"
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: microsoft/playwright-github-action@v1
      - name: install
        run: yarn install
      - name: Check environment
        run: |
          node bin/env.js
      - uses: ./actions/cleanup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Setup NVDA"
        run: |
          $LOG_FILE_PATH = "${{ github.workspace }}\lib\a11y-snapshot\nvda.log"
          $CONFIG_PATH = "${{ env.NVDA_VENDOR }}\settings"
          & ${{ env.NVDA_BIN }} --log-file=$LOG_FILE_PATH --config-path=$CONFIG_PATH
      - uses: ./actions/watch-material-ui
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Teardown NVDA"
        run: |
          & ${{ env.NVDA_BIN }} -q
